FROM maven:3-jdk-11
ADD . /build
WORKDIR /build
RUN mvn clean package -B
 
FROM openjdk:11-jdk
COPY --from=0 "/build/target/rctDataServer-*-SNAPSHOT.jar" app.jar
CMD [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
