FROM maven:3-jdk-11
ADD . /build
WORKDIR /build
RUN mvn clean package -B
 
FROM openjdk:11-jdk
COPY --from=0 "/build/target/rctDataServer-*.jar" app.jar
CMD [ "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar" ]
